Wip master
learn-co-curriculum/react-type-ahead-wikipedia-search-lab pull request #2
Opened 2016-09-30 01:09 UTC by alexanderGugel

Seems kind of weird to do this without a dispatcher though...
The store tests are still the same... maybe a bit too short.

Not sure yet how to best test the actions in this case without mocking out jsonp...

Thoughts?

2016-10-04 08:07 UTC, thomastuts requested changes
@alexanderGugel Great stuff yet again! I like how we also transform the data instead of using it as-is — makes students think about data structures. Good job! 🔥

2016-10-04 08:07 UTC, thomastuts commented on README.md
> +2. The last time the store was updated.
This numbering is messed up (displays as `1. The last...`)

2016-10-04 08:07 UTC, thomastuts commented on package.json
> +    "jsonp": "^0.2.0",
Needs `sinon` as a dependency

2016-10-04 08:09 UTC, thomastuts commented
For testing the XHR stuff, you can use `fetch` instead and use `fetch-mock` like in [this lab](https://github.com/learn-co-curriculum/react-props-and-state-lab/blob/master/fetch-setup.js).

2016-10-07 00:55 UTC, alexanderGugel commented
@thomastuts it looks like we have to use JSONP. The API doesn't allow CORS (https://phabricator.wikimedia.org/T62835).

2016-10-07 01:30 UTC, alexanderGugel commented
@thomastuts In order to make things testable, I extracted out the "minimal" possible Wikipedia API. This makes things easier to test without hacking around `require` and also makes it easier for students to concentrate on the actual action creators — instead of fighting with CORS issues etc.

2016-10-10 07:33 UTC, thomastuts commented
@alexanderGugel This looks great! Good solution for the XHR stuff, too. Nice job! 💣

2016-10-10 07:34 UTC, merged