Master fix
learn-co-curriculum/react-type-ahead-wikipedia-search-lab pull request #3
Opened 2016-11-07 16:51 UTC by aturkewi

@Lukeghenco Can you take a look at this?

The biggest change was had to change a test from `calledOnce` is just `called`. For some reason, the test was registering as it being called twice.

2016-11-07 19:26 UTC, Lukeghenco requested changes
Thanks Avidor. Change back to pure components though.

2016-11-07 19:26 UTC, Lukeghenco commented on components/SearchField.js
> +class SearchField extends React.Component {
const is more accurate here as this should be a `pure/stateless` component. You only create Classes if they hold state.

2016-11-07 19:26 UTC, Lukeghenco commented on components/SearchResults.js
> +class SearchResults extends React.Component {
const is more accurate here as this should be a pure/stateless component. You only create Classes if they hold state.

2016-11-07 19:26 UTC, Lukeghenco commented on test/Autocomplete-test.js
> +  it('should have class .autocomplete', function() {
haha, for sure. These seem like unneeded tests though.

2016-11-07 19:26 UTC, Lukeghenco commented on test/SearchResults-test.js
> +  it('should render an <ul>', function() {
LGTM 👍  If this was a component though I would add those self closing tags. Example `<AutoComplete />`

2016-11-07 19:26 UTC, Lukeghenco commented on README.md
> -![Screenshot](./assets/screenshot.png)
All of this text stuff looks good

2016-11-08 23:22 UTC, aturkewi commented
Made the changes. Thanks @Lukeghenco

2016-11-08 23:22 UTC, merged